language: node_js
node_js:
  - "node"
services:
  - postgresql
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database trailblazers_reviews;' -U postgres
  - psql -d "trailblazers_reviews" -c 'CREATE TABLE reviews ( id serial, review_id int, rating int, reviewer varchar(255), title varchar(255), body text, recommend boolean, helpful int, unhelpful int, PRIMARY KEY (id));' -U postgres

jobs:
  include:
    - stage: Lint
    - script: npm run lint
  include: 
    - stage: Test
    - script: npm test
  include:
    - stage: Produce Coverage
    - script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
